# STAGE 1: Build the React App
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npx tsc --noUnusedLocals false --noUnusedParameters false && npx vite build

# STAGE 2: Serve the App with Nginx
FROM nginx:stable-alpine

# Copy the static files from the builder stage to Nginx's default public folder
# Change "dist" to "build" if you are not using Vite
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]